"""empty message

Revision ID: ebc1311e14e6
Revises: 7d92eccc9e14
Create Date: 2025-04-20 10:57:32.223996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc1311e14e6'
down_revision = '7d92eccc9e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
